# Generated by Django 3.0.5 on 2020-04-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='phoneno',
        ),
    ]
